kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: maven
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - mvn clean install

- name: test
  image: maven
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - mvn verify

- name: sonar
  image: maven
  environment:
    SONAR_HOST_URL: http://172.203.224.203:9000
    SONAR_LOGIN:
      from_secret: sonar_token
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - mvn clean verify sonar:sonar -Dsonar.projectKey=App-Test -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN

- name: publish
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: maniacalknight9/hotel-quarkus-app
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
    dockerfile: Hotel/backend/sistema-hoteles-be/src/main/docker/Dockerfile.jvm
    context: Hotel/backend/sistema-hoteles-be

- name: email
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    username:
      from_secret: email_username
    password:
      from_secret: email_password
    from.address: noreply@github.com
    recipients:
      - rodas171315@unis.edu.gt
    subject: "Drone Build Notification"
