kind: pipeline
type: docker
name: frontend

steps:
- name: build

- name: test

- name: publish 
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: maniacalknight9/proyecto-b2b
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest

- name: deploy
