kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: maven
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - mvn clean install

- name: test
  image: maven
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - mvn verify

- name: sonar
  image: maven
  environment:
    SONAR_HOST_URL: http://172.203.224.203:9000
    SONAR_LOGIN:
      from_secret: sonar_token
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - mvn clean verify sonar:sonar -Dsonar.projectKey=App-Test -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

- name: publish
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: maniacalknight9/hotel-quarkus-app
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
    dockerfile: Hotel/backend/sistema-hoteles-be/src/main/docker/Dockerfile.jvm
    context: Hotel/backend/sistema-hoteles-be

- name: deploy
  image: docker
  commands:
    - cd Hotel/
    - docker pull maniacalknight9/hotel-quarkus-app:latest

- name: notify
  pull: if-not-exists
  image: drillster/drone-email
  settings:
    host: smtp.gmail.com
    port: 587 #25
    username:
      from_secret: email_username
    password:
      from_secret: email_password
    from:
      rodas171315@unis.edu.gt
    from.name: Drone Pipeline
    recipients:
      - proyectos.sistemas.mk9@gmail.com
    subject: >
          "Drone Build Notification"
          [{{ build.status }}]
          {{ repo.owner }}/{{ repo.name }}
          ({{ build.branch }} - {{ truncate build.commit 8 }})
  when:
    status:
      include:
        - success
        - failure
