version: "3.7"    

services:
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 2000:3000
    networks:
      - monitor-net
      - hotel-net

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      - '--web.enable-lifecycle'
    networks:
      - monitor-net
      - hotel-net

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    ###### linux
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    ###### windows
    # command: 
    #  - '--path.procfs=/host/proc' 
    #  - '--path.sysfs=/host/sys'
    #  - --collector.filesystem.ignored-mount-points
    #  - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    # volumes:
    #  - /proc:/host/proc:ro
    #  - /sys:/host/sys:ro
    networks:
      - monitor-net
      - hotel-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitor-net
      - hotel-net
    
  # app_example:
  #   image: quay.io/brancz/prometheus-example-app:v0.3.0
  #   container_name: app_example
  #   restart: unless-stopped
  #   ports:
  #   - 80:8080

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitor-net:
    name: monitor-network
    driver: bridge
  hotel-net:
    name: hotel-network
    driver: bridge
