version: "4"

services:
  sonar-db:
    container_name: sonar-db
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - sonar-net
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-temp:/opt/sonarqube/temp
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"
    depends_on:
      - sonar-db
    networks:
      - sonar-net

volumes:
  postgresql:
  postgresql-data:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  sonarqube-temp:
  sonarqube-bundled-plugins:

networks:
  sonar-net:
    name: sonar-network
    driver: bridge
